# Development data sources
datasource:
  runelite:
    jndiName:
    driverClassName: com.mysql.jdbc.Driver
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/runelite
    username: runelite
    password: runelite
  runelite-cache:
    jndiName:
    driverClassName: com.mysql.jdbc.Driver
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/runelite-cache2
    username: runelite
    password: runelite
  runelite-tracker:
    jndiName:
    driverClassName: com.mysql.jdbc.Driver
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/runelite-tracker
    username: runelite
    password: runelite
